///
/// hardware model
///
#ifndef _HW_MODEL_
#define _HW_MODEL_

#include "HWModel.h"
#include "HWModel_3c59x.h"
#include "HWModel_acp3x.h"
#include "HWModel_adv_pci1760.h"
#include "HWModel_aic7xxx.h"
#include "HWModel_amd_xgbe.h"
#include "HWModel_amdgpu.h"
#include "HWModel_applicom.h"
#include "HWModel_arcmsr.h"
#include "HWModel_mISDNinfineon.h"
#include "HWModel_mgag200.h"
#include "HWModel_mlx5.h"
#include "HWModel_mlxsw_spectrum.h"
#include "HWModel_mt76x0e.h"
#include "HWModel_myrb.h"
#include "HWModel_net2272.h"
#include "HWModel_netjet.h"
#include "HWModel_nicstar.h"
#include "HWModel_pata_pdc202xx_old.h"
#include "HWModel_pc300too.h"
#include "HWModel_pci200syn.h"
#include "HWModel_pcnet32.h"
#include "HWModel_pcwd_pci.h"
#include "HWModel_plx_pci.h"
#include "HWModel_pm2fb.h"
#include "HWModel_r8169.h"
#include "HWModel_rtsx_pci.h"
#include "HWModel_rtw88_8822ce.h"
#include "HWModel_s2io.h"
#include "HWModel_sfc.h"
#include "HWModel_sis190.h"
#include "HWModel_skge.h"
#include "HWModel_sky2.h"
#include "HWModel_snd_ad1889.h"
#include "HWModel_snd_hda_intel.h"
#include "HWModel_snd_intel8x0.h"
#include "HWModel_snd_intel8x0m.h"
#include "HWModel_snd_trident.h"
#include "HWModel_solo6x10.h"
#include "HWModel_sundance.h"
#include "HWModel_tlan.h"
#include "HWModel_tsi721.h"
#include "HWModel_ufshcd_pci.h"
#include "HWModel_via_rhine.h"
#include "HWModel_via_velocity.h"
#include "HWModel_vme_ca91cx42.h"
#include "HWModel_vme_tsi148.h"
#include "HWModel_vmw_pvrdma.h"
#include "HWModel_vmxnet3.h"
#include "HWModel_vxge.h"
#include "HWModel_w6692.h"
#include "HWModel_wanxl.h"
#include "HWModel_zatm.h"

HWModel *init_hw_instance(const char *name);
HWModel *init_hw_instance(const std::string &);
HWModel *get_hw_instance();

#endif //_HW_MODEL_
